export { Alquiler, Venta };

var Alquiler = {
  1: {
    nombre: "Ferretti 48 pies",
    capacidad: "10 personas",
    img1: "img/Barco1/Ferretti_48_pies.jpg",
    img2: "img/Barco1/Ferretti_48_pies1.jpg",
    img3: "img/Barco1/Ferretti_48_pies2.jpg",
    img4: "img/Barco1/Ferretti_48_pies3.jpg",
    img5: "img/Barco1/Ferretti_48_pies4.jpg",
    img6: "img/Barco1/Ferretti_48_pies5.jpg",
    img7: "img/Barco1/Ferretti_48_pies6.jpg",
    img8: "img/Barco1/Ferretti_48_pies7.jpg",
    img9: "img/Barco1/Ferretti_48_pies8.jpg",
    img10: "img/Barco1/Ferretti_48_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  2: {
    nombre: "Sunseeker predator 58 pies",
    capacidad: "10 personas",
    img1: "img/Barco2/Sunseeker_predator_58_pies7.jpg",
    img2: "img/Barco2/Sunseeker_predator_58_pies1.jpg",
    img3: "img/Barco2/Sunseeker_predator_58_pies2.jpg",
    img4: "img/Barco2/Sunseeker_predator_58_pies3.jpg",
    img5: "img/Barco2/Sunseeker_predator_58_pies4.jpg",
    img6: "img/Barco2/Sunseeker_predator_58_pies5.jpg",
    img7: "img/Barco2/Sunseeker_predator_58_pies6.jpg",
    img8: "img/Barco2/Sunseeker_predator_58_pies.jpg",
    img9: "img/Barco2/Sunseeker_predator_58_pies8.jpg",
    img10: "img/Barco2/Sunseeker_predator_58_pies9.jpg",
    img11: "img/Barco2/Sunseeker_predator_58_pies10.jpg",
    img12: "img/Barco2/Sunseeker_predator_58_pies11.jpg",
    img13: "img/Barco2/Sunseeker_predator_58_pies12.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  3: {
    nombre: "Ferretti 48 pies",
    capacidad: "10 personas",
    img1: "img/Barco3/Cris_Craft_52_pies.jpg",
    img2: "img/Barco3/Cris_Craft_52_pies1.jpg",
    img3: "img/Barco3/Cris_Craft_52_pies2.jpg",
    img4: "img/Barco3/Cris_Craft_52_pies3.jpg",
    img5: "img/Barco3/Cris_Craft_52_pies4.jpg",
    img6: "img/Barco3/Cris_Craft_52_pies5.jpg",
    img7: "img/Barco3/Cris_Craft_52_pies6.jpg",
    img8: "img/Barco3/Cris_Craft_52_pies7.jpg",
    img9: "img/Barco3/Cris_Craft_52_pies8.jpg",
    img10: "img/Barco3/Cris_Craft_52_pies9.jpg",
    img11: "img/Barco3/Cris_Craft_52_pies10.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  4: {
    nombre: "Ferretti 48 pies",
    capacidad: "10 personas",
    img1: "img/Barco1/Ferretti_48_pies.jpg",
    img2: "img/Barco1/Ferretti_48_pies1.jpg",
    img3: "img/Barco1/Ferretti_48_pies2.jpg",
    img4: "img/Barco1/Ferretti_48_pies3.jpg",
    img5: "img/Barco1/Ferretti_48_pies4.jpg",
    img6: "img/Barco1/Ferretti_48_pies5.jpg",
    img7: "img/Barco1/Ferretti_48_pies6.jpg",
    img8: "img/Barco1/Ferretti_48_pies7.jpg",
    img9: "img/Barco1/Ferretti_48_pies8.jpg",
    img10: "img/Barco1/Ferretti_48_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  5: {
    nombre: "Ferretti 48 pies",
    capacidad: "10 personas",
    img1: "img/Barco1/Ferretti_48_pies.jpg",
    img2: "img/Barco1/Ferretti_48_pies1.jpg",
    img3: "img/Barco1/Ferretti_48_pies2.jpg",
    img4: "img/Barco1/Ferretti_48_pies3.jpg",
    img5: "img/Barco1/Ferretti_48_pies4.jpg",
    img6: "img/Barco1/Ferretti_48_pies5.jpg",
    img7: "img/Barco1/Ferretti_48_pies6.jpg",
    img8: "img/Barco1/Ferretti_48_pies7.jpg",
    img9: "img/Barco1/Ferretti_48_pies8.jpg",
    img10: "img/Barco1/Ferretti_48_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  6: {
    nombre: "Ferretti 48 pies",
    capacidad: "10 personas",
    img1: "img/Barco1/Ferretti_48_pies.jpg",
    img2: "img/Barco1/Ferretti_48_pies1.jpg",
    img3: "img/Barco1/Ferretti_48_pies2.jpg",
    img4: "img/Barco1/Ferretti_48_pies3.jpg",
    img5: "img/Barco1/Ferretti_48_pies4.jpg",
    img6: "img/Barco1/Ferretti_48_pies5.jpg",
    img7: "img/Barco1/Ferretti_48_pies6.jpg",
    img8: "img/Barco1/Ferretti_48_pies7.jpg",
    img9: "img/Barco1/Ferretti_48_pies8.jpg",
    img10: "img/Barco1/Ferretti_48_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  7: {},
  8: {},
  9: {},
  10: {},
  11: {},
  12: {},
};

var Venta = {
  1: {
    nombre: "Nombre de prueba",
    capacidad: "4 personas",
    img1: "img/yate.jpg",
    img2: "img/yate.jpg",
    img3: "img/yate.jpg",
    img4: "img/yate.jpg",
    img5: "img/yate.jpg",
    img6: "img/yate.jpg",
    img7: "img/yate.jpg",
    img8: "img/yate.jpg",
    img9: "img/yate.jpg",
    img10: "img/yate.jpg",
    equipo: {
      camarote: "3 Camarotes",
      baño: "",
      sala: "Sala",
      chalecos: "",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "",
      acondicionado: "",
      cocina: "Cocina",
      comedor: "",
      regadera: "",
      gps: "",
      kayak: "",
      snorkel: "Snorkel",
      salvavidas: "",
      lancha: "",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "12 Aguas",
      cerveza: "12 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "",
      marinero: "",
    },
  },
  2: {},
  3: {},
  4: {},
  5: {},
  6: {},
  7: {},
  8: {},
  9: {},
  10: {},
  11: {},
  12: {},
};
