export { Alquiler, Venta };

var Alquiler = {
  1: {
    nombre: "Ferretti 48 pies",
    capacidad: "10 personas",
    img1: "img/Barco1/Ferretti_48_pies.jpg",
    img2: "img/Barco1/Ferretti_48_pies1.jpg",
    img3: "img/Barco1/Ferretti_48_pies2.jpg",
    img4: "img/Barco1/Ferretti_48_pies3.jpg",
    img5: "img/Barco1/Ferretti_48_pies4.jpg",
    img6: "img/Barco1/Ferretti_48_pies5.jpg",
    img7: "img/Barco1/Ferretti_48_pies6.jpg",
    img8: "img/Barco1/Ferretti_48_pies7.jpg",
    img9: "img/Barco1/Ferretti_48_pies8.jpg",
    img10: "img/Barco1/Ferretti_48_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  2: {
    nombre: "Sunseeker predator 58 pies",
    capacidad: "10 personas",
    img1: "img/Barco2/Sunseeker_predator_58_pies7.jpg",
    img2: "img/Barco2/Sunseeker_predator_58_pies1.jpg",
    img3: "img/Barco2/Sunseeker_predator_58_pies2.jpg",
    img4: "img/Barco2/Sunseeker_predator_58_pies3.jpg",
    img5: "img/Barco2/Sunseeker_predator_58_pies4.jpg",
    img6: "img/Barco2/Sunseeker_predator_58_pies5.jpg",
    img7: "img/Barco2/Sunseeker_predator_58_pies6.jpg",
    img8: "img/Barco2/Sunseeker_predator_58_pies.jpg",
    img9: "img/Barco2/Sunseeker_predator_58_pies8.jpg",
    img10: "img/Barco2/Sunseeker_predator_58_pies9.jpg",
    img11: "img/Barco2/Sunseeker_predator_58_pies10.jpg",
    img12: "img/Barco2/Sunseeker_predator_58_pies11.jpg",
    img13: "img/Barco2/Sunseeker_predator_58_pies12.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  3: {
    nombre: "Cris Craft 52 pies",
    capacidad: "10 personas",
    img1: "img/Barco3/Cris_Craft_52_pies.jpg",
    img2: "img/Barco3/Cris_Craft_52_pies1.jpg",
    img3: "img/Barco3/Cris_Craft_52_pies2.jpg",
    img4: "img/Barco3/Cris_Craft_52_pies3.jpg",
    img5: "img/Barco3/Cris_Craft_52_pies4.jpg",
    img6: "img/Barco3/Cris_Craft_52_pies5.jpg",
    img7: "img/Barco3/Cris_Craft_52_pies6.jpg",
    img8: "img/Barco3/Cris_Craft_52_pies7.jpg",
    img9: "img/Barco3/Cris_Craft_52_pies8.jpg",
    img10: "img/Barco3/Cris_Craft_52_pies9.jpg",
    img11: "img/Barco3/Cris_Craft_52_pies10.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  4: {
    nombre: "Sea Ray Deportivo 46 pies",
    capacidad: "10 personas",
    img1: "img/Barco4/Sea_Ray_Deportivo_46_pies.jpg",
    img2: "img/Barco4/Sea_Ray_Deportivo_46_pies1.jpg",
    img3: "img/Barco4/Sea_Ray_Deportivo_46_pies2.jpg",
    img4: "img/Barco4/Sea_Ray_Deportivo_46_pies3.jpg",
    img5: "img/Barco4/Sea_Ray_Deportivo_46_pies4.jpg",
    img6: "img/Barco4/Sea_Ray_Deportivo_46_pies5.jpg",
    img7: "img/Barco4/Sea_Ray_Deportivo_46_pies6.jpg",
    img8: "img/Barco4/Sea_Ray_Deportivo_46_pies7.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  5: {
    nombre: "Sea Ray 37 pies",
    capacidad: "10 personas",
    img1: "img/Bsrco5/Sea_Ray_37_pies.jpg",
    img2: "img/Bsrco5/Sea_Ray_37_pies1.jpg",
    img3: "img/Bsrco5/Sea_Ray_37_pies2.jpg",
    img4: "img/Bsrco5/Sea_Ray_37_pies3.jpg",
    img5: "img/Bsrco5/Sea_Ray_37_pies4.jpg",
    img6: "img/Bsrco5/Sea_Ray_37_pies5.jpg",
    img7: "img/Bsrco5/Sea_Ray_37_pies6.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  6: {
    nombre: "Hatteras 52 pies",
    capacidad: "10 personas",
    img1: "img/Barco6/Hatteras_52_pies.jpg",
    img2: "img/Barco6/Hatteras_52_pies1.jpg",
    img3: "img/Barco6/Hatteras_52_pies2.jpg",
    img4: "img/Barco6/Hatteras_52_pies3.jpg",
    img5: "img/Barco6/Hatteras_52_pies4.jpg",
    img6: "img/Barco6/Hatteras_52_pies5.jpg",
    img7: "img/Barco6/Hatteras_52_pies6.jpg",
    img8: "img/Barco6/Hatteras_52_pies7.jpg",
    img9: "img/Barco6/Hatteras_52_pies8.jpg",
    img10: "img/Barco6/Hatteras_52_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  7: {
    nombre: "Sea Ray 50 pies",
    capacidad: "10 personas",
    img1: "img/Barco7/Sea_Ray_50_pies.jpg",
    img2: "img/Barco7/Sea_Ray_50_pies1.jpg",
    img3: "img/Barco7/Sea_Ray_50_pies2.jpg",
    img4: "img/Barco7/Sea_Ray_50_pies3.jpg",
    img5: "img/Barco7/Sea_Ray_50_pies4.jpg",
    img6: "img/Barco7/Sea_Ray_50_pies5.jpg",
    img7: "img/Barco7/Sea_Ray_50_pies6.jpg",
    img8: "img/Barco7/Sea_Ray_50_pies7.jpg",
    img9: "img/Barco7/Sea_Ray_50_pies8.jpg",
    img10: "img/Barco7/Sea_Ray_50_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  8: {
    nombre: "Sea Ray Deportivo 55 pies",
    capacidad: "10 personas",
    img1: "img/Barco8/Sea_Ray_Deportivo_55_pies.jpg",
    img2: "img/Barco8/Sea_Ray_Deportivo_55_pies1.jpg",
    img3: "img/Barco8/Sea_Ray_Deportivo_55_pies2.jpg",
    img4: "img/Barco8/Sea_Ray_Deportivo_55_pies3.jpg",
    img5: "img/Barco8/Sea_Ray_Deportivo_55_pies4.jpg",
    img6: "img/Barco8/Sea_Ray_Deportivo_55_pies5.jpg",
    img7: "img/Barco8/Sea_Ray_Deportivo_55_pies6.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  9: {
    nombre: "Náutica 48 pies",
    capacidad: "10 personas",
    img1: "img/Barco9/Náutica_48_pies.jpg",
    img2: "img/Barco9/Náutica_48_pies1.jpg",
    img3: "img/Barco9/Náutica_48_pies2.jpg",
    img4: "img/Barco9/Náutica_48_pies3.jpg",
    img5: "img/Barco9/Náutica_48_pies4.jpg",
    img6: "img/Barco9/Náutica_48_pies5.jpg",
    img7: "img/Barco9/Náutica_48_pies6.jpg",
    img8: "img/Barco9/Náutica_48_pies7.jpg",
    img9: "img/Barco9/Náutica_48_pies8.jpg",
    img10: "img/Barco9/Náutica_48_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  10: {
    nombre: "Striker 52 pies",
    capacidad: "10 personas",
    img1: "img/Barco10/Striker_52_pies.jpg",
    img2: "img/Barco10/Striker_52_pies1.jpg",
    img3: "img/Barco10/Striker_52_pies2.jpg",
    img4: "img/Barco10/Striker_52_pies3.jpg",
    img5: "img/Barco10/Striker_52_pies4.jpg",
    img6: "img/Barco10/Striker_52_pies5.jpg",
    img7: "img/Barco10/Striker_52_pies6.jpg",
    img8: "img/Barco10/Striker_52_pies7.jpg",
    img9: "img/Barco10/Striker_52_pies8.jpg",
    img10: "img/Barco10/Striker_52_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  11: {
    nombre: "Velero Clásico 54 pies",
    capacidad: "10 personas",
    img1: "img/Barco11/Velero_Clásico_54_pies.jpg",
    img2: "img/Barco11/Velero_Clásico_54_pies1.jpg",
    img3: "img/Barco11/Velero_Clásico_54_pies2.jpg",
    img4: "img/Barco11/Velero_Clásico_54_pies3.jpg",
    img5: "img/Barco11/Velero_Clásico_54_pies4.jpg",
    img6: "img/Barco11/Velero_Clásico_54_pies5.jpg",
    img7: "img/Barco11/Velero_Clásico_54_pies6.jpg",
    img8: "img/Barco11/Velero_Clásico_54_pies7.jpg",
    img9: "img/Barco11/Velero_Clásico_54_pies8.jpg",
    img10: "img/Barco11/Velero_Clásico_54_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  12: {
    nombre: "Sunseeker 74 pies",
    capacidad: "10 personas",
    img1: "img/Barco12/Sunseeker_74_pies.jpg",
    img2: "img/Barco12/Sunseeker_74_pies1.jpg",
    img3: "img/Barco12/Sunseeker_74_pies2.jpg",
    img4: "img/Barco12/Sunseeker_74_pies3.jpg",
    img5: "img/Barco12/Sunseeker_74_pies4.jpg",
    img6: "img/Barco12/Sunseeker_74_pies5.jpg",
    img7: "img/Barco12/Sunseeker_74_pies6.jpg",
    img8: "img/Barco12/Sunseeker_74_pies7.jpg",
    img9: "img/Barco12/Sunseeker_74_pies8.jpg",
    img10: "img/Barco12/Sunseeker_74_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },

  13: {
    nombre: "Hatteras_76_pies",
    capacidad: "10 personas",
    img1: "img/Barco13/Hatteras_76_pies.jpg",
    img2: "img/Barco13/Hatteras_76_pies1.jpg",
    img3: "img/Barco13/Hatteras_76_pies2.jpg",
    img4: "img/Barco13/Hatteras_76_pies3.jpg",
    img5: "img/Barco13/Hatteras_76_pies4.jpg",
    img6: "img/Barco13/Hatteras_76_pies5.jpg",
    img7: "img/Barco13/Hatteras_76_pies6.jpg",
    img8: "img/Barco13/Hatteras_76_pies7.jpg",
    img9: "img/Barco13/Hatteras_76_pies8.jpg",
    img10: "img/Barco13/Hatteras_76_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },

  14: {
    nombre: "Bertram 64 pies",
    capacidad: "10 personas",
    img1: "img/Barco14/Bertram_64_pies.jpg",
    img2: "img/Barco14/Bertram_64_pies1.jpg",
    img3: "img/Barco14/Bertram_64_pies2.jpg",
    img4: "img/Barco14/Bertram_64_pies3.jpg",
    img5: "img/Barco14/Bertram_64_pies4.jpg",
    img6: "img/Barco14/Bertram_64_pies5.jpg",
    img7: "img/Barco14/Bertram_64_pies6.jpg",
    img8: "img/Barco14/Bertram_64_pies7.jpg",
    img9: "img/Barco14/Bertram_64_pies8.jpg",
    img10: "img/Barco14/Bertram_64_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },

  15: {
    nombre: "Ocean 42 pies",
    capacidad: "10 personas",
    img1: "img/Barco15/Ocean_42_pies.jpg",
    img2: "img/Barco15/Ocean_42_pies1.jpg",
    img3: "img/Barco15/Ocean_42_pies2.jpg",
    img4: "img/Barco15/Ocean_42_pies3.jpg",
    img5: "img/Barco15/Ocean_42_pies4.jpg",
    img6: "img/Barco15/Ocean_42_pies5.jpg",
    img7: "img/Barco15/Ocean_42_pies6.jpg",
    img8: "img/Barco15/Ocean_42_pies7.jpg",
    img9: "img/Barco15/Ocean_42_pies8.jpg",
    img10: "img/Barco15/Ocean_42_pies9.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },

  16: {
    nombre: "Sunseeker 44 pies",
    capacidad: "10 personas",
    img1: "img/Barco16/Sunseeker_44_pies.jpg",
    img2: "img/Barco16/Sunseeker_44_pies1.jpg",
    img3: "img/Barco16/Sunseeker_44_pies2.jpg",
    img4: "img/Barco16/Sunseeker_44_pies3.jpg",
    img5: "img/Barco16/Sunseeker_44_pies4.jpg",
    img6: "img/Barco16/Sunseeker_44_pies5.jpg",
    img7: "img/Barco16/Sunseeker_44_pies6.jpg",
    img8: "img/Barco16/Sunseeker_44_pies7.jpg",
    img9: "img/Barco16/Sunseeker_44_pies8.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
};

var Venta = {
  1: {
    nombre: "Cris Craft 52 pies",
    capacidad: "10 personas",
    img1: "img/Barco3/Cris_Craft_52_pies.jpg",
    img2: "img/Barco3/Cris_Craft_52_pies1.jpg",
    img3: "img/Barco3/Cris_Craft_52_pies2.jpg",
    img4: "img/Barco3/Cris_Craft_52_pies3.jpg",
    img5: "img/Barco3/Cris_Craft_52_pies4.jpg",
    img6: "img/Barco3/Cris_Craft_52_pies5.jpg",
    img7: "img/Barco3/Cris_Craft_52_pies6.jpg",
    img8: "img/Barco3/Cris_Craft_52_pies7.jpg",
    img9: "img/Barco3/Cris_Craft_52_pies8.jpg",
    img10: "img/Barco3/Cris_Craft_52_pies9.jpg",
    img11: "img/Barco3/Cris_Craft_52_pies10.jpg",
    equipo: {
      camarote: "2 Camarotes",
      baño: "1 baños",
      ducha: "1 ducha",
      sala: "Sala",
      cocina: "Cocina",
      chalecos: "Chalecos Salvavidas",
      sonido: "Sonido Bluetooth",
      hielera: "Hielera",
      pesca: "Equipo de Pesca",
      acondicionado: "Aire Acondicionado",
      comedor: "Comedor",
      regadera: "2 Regaderas",
      gps: "Gps",
      kayak: "Equipo Kayak",
      snorkel: "Snorkel",
      salvavidas: "Aros Salvavidas",
      lancha: "Lancha Neumática",
    },
    incluye: {
      refresco: "2 Refrescos",
      agua: "20 Aguas",
      cerveza: "20 Cervezas",
      hielo: "Hielo",
      vasos: "Vasos",
      capitan: "1 Capitan",
      marinero: "1 Marinero",
    },
  },
  2: {},
  3: {},
  4: {},
  5: {},
  6: {},
  7: {},
  8: {},
  9: {},
  10: {},
  11: {},
  12: {},
};
